### ISSUE TITLE
Doesn't work anymore (mb cause of the newest versions of tensorflow) - TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by anonym24** [penseeartificielle/mobilenet-ssd-detection-example#1]
```
Traceback (most recent call last):
  File "test-video-example.py", line 140, in <module>
    feed_dict={image_tensor: image_np_expanded})
  File "D:\ProgramFiles\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "D:\ProgramFiles\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\client\session.py", line 1079, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "D:\ProgramFiles\anaconda3\envs\tensorflow1\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by AshwinRaikar88** [comment]
If you're using tf 2.0 try importing tf as 
import tensorflow.compat.v1 as tf
